/**
 * Result of a plugin task execution.
 *
 * Contains the outcome status of a task and any additional result data.
 */
export interface PluginTaskResult<T> {
    /**
     * Optional result data from the task execution.
     */
    data?: T;
}

/**
 * Request message sent from server to plugin.
 *
 * Contains a unique identifier, task name, and parameters for execution.
 */
export interface PluginTaskRequest {
    /**
     * Unique identifier for request/response correlation.
     */
    id: string;

    /**
     * The name of the task to execute.
     */
    task: string;

    /**
     * The parameters for task execution.
     */
    params: any;
}

/**
 * Response message sent from plugin back to server.
 *
 * Contains the original request ID and the execution result.
 */
export interface PluginTaskResponse<T> {
    /**
     * Unique identifier matching the original request.
     */
    id: string;

    /**
     * Whether the task completed successfully.
     */
    success: boolean;

    /**
     * Optional error message if the task failed.
     */
    error?: string;

    /**
     * The result of the task execution.
     */
    data?: T;
}

export type PluginMessageType = "task-response" | "file-context-update";

export type FileContextStatus = "available" | "bound" | "stale" | "released" | "error";

export interface FileContextSnapshot {
    /**
     * Stable context identifier for the reporting plugin instance and file.
     */
    contextId: string;

    /**
     * Current context status as reported or derived by the server registry.
     */
    status: FileContextStatus;

    /**
     * Browser/plugin owner identifier. In the first implementation this is the
     * background plugin instance id.
     */
    ownerTabId: string;

    /**
     * Current file id.
     */
    fileId: string;

    /**
     * Current file display name.
     */
    fileName?: string;

    /**
     * File revision number reported by the plugin API when available.
     */
    revn?: number;

    /**
     * Active page id and name when a workspace page is available.
     */
    pageId?: string;
    pageName?: string;

    /**
     * Currently selected shape ids.
     */
    selectionIds: string[];

    /**
     * Optional project and team ids. The plugin API does not always expose
     * these, so server-side tools must treat them as advisory.
     */
    projectId?: string;
    teamId?: string;

    /**
     * File-scoped capabilities available through this context.
     */
    capabilities: string[];

    /**
     * ISO timestamp generated by the reporting plugin.
     */
    updatedAt: string;
}

export interface PluginFileContextUpdateMessage {
    type: "file-context-update";
    context: FileContextSnapshot | null;
    reason?: string;
}

export interface WrappedPluginTaskResponse<T> {
    type: "task-response";
    response: PluginTaskResponse<T>;
}

export type PluginToServerMessage<T> =
    | PluginTaskResponse<T>
    | WrappedPluginTaskResponse<T>
    | PluginFileContextUpdateMessage;

/**
 * Parameters for the executeCode task.
 */
export interface ExecuteCodeTaskParams {
    /**
     * The JavaScript code to be executed.
     */
    code: string;
}

/**
 * Result data for the executeCode task.
 */
export interface ExecuteCodeTaskResultData<T> {
    /**
     * The result of the executed code, if any.
     */
    result: T;

    /**
     * Captured console output during code execution.
     */
    log: string;
}
