/**
 * Result of a plugin task execution.
 *
 * Contains the outcome status of a task and any additional result data.
 */
export interface PluginTaskResult<T> {
    /**
     * Optional result data from the task execution.
     */
    data?: T;
}

/**
 * Request message sent from server to plugin.
 *
 * Contains a unique identifier, task name, and parameters for execution.
 */
export interface PluginTaskRequest {
    /**
     * Unique identifier for request/response correlation.
     */
    id: string;

    /**
     * The name of the task to execute.
     */
    task: string;

    /**
     * The parameters for task execution.
     */
    params: any;
}

/**
 * Response message sent from plugin back to server.
 *
 * Contains the original request ID and the execution result.
 */
export interface PluginTaskResponse<T> {
    /**
     * Unique identifier matching the original request.
     */
    id: string;

    /**
     * Whether the task completed successfully.
     */
    success: boolean;

    /**
     * Optional error message if the task failed.
     */
    error?: string;

    /**
     * The result of the task execution.
     */
    data?: T;
}

export const MCP_PROTOCOL_VERSION = "1.0";

export const MCP_SERVER_VERSION = "1.0.0";

export const MCP_SERVER_CAPABILITIES = [
    "global.read",
    "file-context.read",
    "file-context.bind",
    "page.read",
    "page.write",
    "selection.read",
    "selection.write",
    "shape.write-basic",
    "prototype.write-basic",
    "export.read",
    "backend-command.write",
    "execute-code.optional",
] as const;

export const MCP_REQUIRED_PLUGIN_CAPABILITIES = [
    "file-context.read",
    "file-context.bind",
    "page.read",
    "page.write",
    "selection.read",
    "selection.write",
    "shape.write-basic",
    "prototype.write-basic",
    "export.read",
] as const;

export type PluginMessageType = "plugin-hello" | "task-response" | "file-context-update";

export interface PluginHelloMessage {
    type: "plugin-hello";
    protocolVersion: string;
    pluginVersion: string;
    penpotVersion?: string;
    frontendVersion?: string;
    capabilities: string[];
    fileContextCapabilities: string[];
    ownerTabId?: string;
    updatedAt: string;
}

export interface PluginClientInfo {
    protocolVersion: string;
    pluginVersion: string;
    penpotVersion?: string;
    frontendVersion?: string;
    capabilities: string[];
    fileContextCapabilities: string[];
    ownerTabId?: string;
    updatedAt: string;
}

export interface ServerPluginCompatibilityMessage {
    type: "plugin-compatibility";
    compatible: boolean;
    serverVersion: string;
    protocolVersion: string;
    supportedCapabilities: string[];
    requiredCapabilities: string[];
    missingCapabilities: string[];
    unsupportedCapabilities: string[];
    error?: {
        code: string;
        message: string;
    };
}

export type FileContextStatus = "available" | "bound" | "stale" | "released" | "error";

export interface FileContextSnapshot {
    /**
     * Stable context identifier for the reporting plugin instance and file.
     */
    contextId: string;

    /**
     * Current context status as reported or derived by the server registry.
     */
    status: FileContextStatus;

    /**
     * Browser/plugin owner identifier. In the first implementation this is the
     * background plugin instance id.
     */
    ownerTabId: string;

    /**
     * Current file id.
     */
    fileId: string;

    /**
     * Current file display name.
     */
    fileName?: string;

    /**
     * File revision number reported by the plugin API when available.
     */
    revn?: number;

    /**
     * Active page id and name when a workspace page is available.
     */
    pageId?: string;
    pageName?: string;

    /**
     * Currently selected shape ids.
     */
    selectionIds: string[];

    /**
     * Optional project and team ids. The plugin API does not always expose
     * these, so server-side tools must treat them as advisory.
     */
    projectId?: string;
    teamId?: string;

    /**
     * File-scoped capabilities available through this context.
     */
    capabilities: string[];

    /**
     * ISO timestamp generated by the reporting plugin.
     */
    updatedAt: string;
}

export interface PluginFileContextUpdateMessage {
    type: "file-context-update";
    context: FileContextSnapshot | null;
    reason?: string;
}

export interface PluginFileContextBindRequestMessage {
    type: "file-context-bind-request";
    requestId: string;
    context: FileContextSnapshot | null;
}

export interface PluginFileContextReleaseRequestMessage {
    type: "file-context-release-request";
    requestId: string;
}

export interface PluginFileContextControlResultMessage {
    type: "file-context-control-result";
    requestId: string;
    action: "bind" | "release";
    success: boolean;
    context?: FileContextSnapshot | null;
    error?: {
        code: string;
        message: string;
    };
}

export interface WrappedPluginTaskResponse<T> {
    type: "task-response";
    response: PluginTaskResponse<T>;
}

export type PluginToServerMessage<T> =
    | PluginTaskResponse<T>
    | WrappedPluginTaskResponse<T>
    | PluginFileContextUpdateMessage
    | PluginFileContextBindRequestMessage
    | PluginFileContextReleaseRequestMessage;

export type ServerToPluginMessage =
    | PluginTaskRequest
    | PluginFileContextControlResultMessage
    | ServerPluginCompatibilityMessage;

/**
 * Parameters for the executeCode task.
 */
export interface ExecuteCodeTaskParams {
    /**
     * The JavaScript code to be executed.
     */
    code: string;
}

/**
 * Result data for the executeCode task.
 */
export interface ExecuteCodeTaskResultData<T> {
    /**
     * The result of the executed code, if any.
     */
    result: T;

    /**
     * Captured console output during code execution.
     */
    log: string;
}

export interface PageSummary {
    id: string;
    name: string;
    current: boolean;
}

export type PageTaskAction = "list" | "create" | "rename" | "setCurrent";

export interface PageTaskParams {
    action: PageTaskAction;
    pageId?: string;
    name?: string;
    makeCurrent?: boolean;
}

export interface PageTaskResultData {
    page?: PageSummary;
    pages: PageSummary[];
    currentPage: PageSummary | null;
}

export interface SelectionShapeSummary {
    id: string;
    name: string;
    type: string;
    pageId?: string;
    pageName?: string;
    parentId?: string;
    x?: number;
    y?: number;
    parentX?: number;
    parentY?: number;
    width?: number;
    height?: number;
}

export type SelectionTaskAction = "get" | "set";

export interface SelectionTaskParams {
    action: SelectionTaskAction;
    shapeIds?: string[];
}

export interface SelectionTaskResultData {
    selectionIds: string[];
    shapes: SelectionShapeSummary[];
    currentPage: PageSummary | null;
}

export interface ShapeSummary {
    id: string;
    name: string;
    type: string;
    pageId?: string;
    pageName?: string;
    parentId?: string;
    x: number;
    y: number;
    parentX?: number;
    parentY?: number;
    width: number;
    height: number;
}

export interface ShapeSolidFill {
    color: string;
    opacity?: number;
}

export interface ShapeStroke {
    color: string;
    opacity?: number;
    width?: number;
    style?: "solid" | "dotted" | "dashed";
    alignment?: "center" | "inner" | "outer";
}

export interface ShapeLayout {
    type: "none" | "flex" | "grid";
    direction?: "row" | "row-reverse" | "column" | "column-reverse";
    wrap?: "wrap" | "nowrap";
    alignItems?: "start" | "end" | "center" | "stretch";
    justifyItems?: "start" | "end" | "center" | "stretch";
    alignContent?: "start" | "center" | "end" | "space-between" | "space-around" | "space-evenly" | "stretch";
    justifyContent?: "start" | "center" | "end" | "space-between" | "space-around" | "space-evenly" | "stretch";
    rowGap?: number;
    columnGap?: number;
    padding?: number;
    rows?: Array<{ type: "percent" | "flex" | "auto" | "fixed"; value?: number }>;
    columns?: Array<{ type: "percent" | "flex" | "auto" | "fixed"; value?: number }>;
}

export type ShapeTaskAction = "createFrame" | "createRect" | "createText" | "createImage" | "update" | "delete";

export interface ShapeTaskParams {
    action: ShapeTaskAction;
    shapeId?: string;
    parentId?: string;
    name?: string;
    x?: number;
    y?: number;
    width?: number;
    height?: number;
    fill?: ShapeSolidFill;
    stroke?: ShapeStroke;
    borderRadius?: number;
    content?: string;
    fontSize?: number;
    layout?: ShapeLayout;
    imageBase64?: string;
    mimeType?: string;
}

export interface ShapeTaskResultData {
    shape: ShapeSummary;
    currentPage: PageSummary | null;
    deleted?: boolean;
}

export interface PrototypeFlowSummary {
    id?: string;
    name: string;
    pageId?: string;
    pageName?: string;
    startingBoardId: string;
    startingBoardName: string;
}

export type PrototypeTrigger = "click" | "mouse-enter" | "mouse-leave" | "after-delay";

export type PrototypeAnimationType = "dissolve" | "slide" | "push";

export interface PrototypeAnimation {
    type: PrototypeAnimationType;
    duration: number;
    easing?: "linear" | "ease" | "ease-in" | "ease-out" | "ease-in-out";
    direction?: "right" | "left" | "up" | "down";
    way?: "in" | "out";
    offsetEffect?: boolean;
}

export type PrototypeInteractionIdentity =
    | {
          kind: "stable-id";
          interactionId: string;
          sourceShapeId: string;
          interactionIndex: number;
      }
    | {
          kind: "source-index";
          sourceShapeId: string;
          interactionIndex: number;
          unstable: true;
      };

export interface PrototypeInteractionSummary {
    interactionId?: string;
    sourceShapeId: string;
    sourceShapeName: string;
    index: number;
    identity: PrototypeInteractionIdentity;
    trigger: PrototypeTrigger;
    delay?: number | null;
    actionType: "navigate-to";
    destinationBoardId: string;
    destinationBoardName: string;
}

export type PrototypeTaskAction = "createFlow" | "createInteraction";

export interface PrototypeTaskParams {
    action: PrototypeTaskAction;
    name?: string;
    startingBoardId?: string;
    sourceShapeId?: string;
    destinationBoardId?: string;
    trigger?: PrototypeTrigger;
    delay?: number;
    preserveScrollPosition?: boolean;
    animation?: PrototypeAnimation;
}

export interface PrototypeTaskResultData {
    flow?: PrototypeFlowSummary;
    interaction?: PrototypeInteractionSummary;
    currentPage: PageSummary | null;
}

export type ExportTaskAction = "exportShape" | "exportPage" | "renderPreview";

export type ExportFormat = "png" | "jpeg" | "svg" | "pdf";

export type ExportTargetType = "shape" | "selection" | "page";

export interface ExportTaskParams {
    action: ExportTaskAction;
    target?: ExportTargetType;
    shapeId?: string;
    pageId?: string;
    format?: ExportFormat;
    scale?: number;
    skipChildren?: boolean;
}

export interface ExportSummary {
    targetType: ExportTargetType;
    targetId?: string;
    targetName?: string;
    pageId?: string;
    pageName?: string;
    format: ExportFormat;
    mimeType: string;
    scale?: number;
    byteLength: number;
    dataBase64: string;
}

export interface ExportTaskResultData {
    export: ExportSummary;
    currentPage: PageSummary | null;
}
